### ISSUE TITLE
error when executing ./undeploy.sh

### ISSUE THREAD

**Issue by lichsmarac** [paulparkinson/msdataworkshop#2]
https://github.com/paulparkinson/msdataworkshop/blob/6769355b77e758987a439656d7a0a43f7da5d142/frontend-helidon/undeploy.sh#L15

When executing /msdataworkshop/frontend-helidon/undeploy.sh , I get the following error:

```
user1@cloudshell:frontend-helidon (us-phoenix-1)$ ./undeploy.sh 
delete frontend-helidon deployment and service...
deployment.extensions "frontend-helidon" deleted
error: the path "./frontend-helidon-service.yaml" does not exist
```

I think the last line should be:
`kubectl delete -f $SCRIPT_DIR/frontend-service.yaml -n msdataworkshop`

**Comment by paulparkinson** [comment]
fixed, thanks!
