### ISSUE TITLE
When apiVersion changed from extensions/v1beta1 to apps/v1 deploy.sh fails

### ISSUE THREAD

**Issue by lichsmarac** [paulparkinson/msdataworkshop#3]
https://github.com/paulparkinson/msdataworkshop/blob/6769355b77e758987a439656d7a0a43f7da5d142/frontend-helidon/frontend-helidon-deployment.yaml#L1

With the apiVersion: apps/v1, the execution of deploy.sh fails to deploy the frontend-helidon pod. 
The following message is displayed:

`msdatawork@cloudshell:frontend-helidon (us-phoenix-1)$ ./deploy.sh`
`error: error validating "./frontend-helidon-deployment.yaml": error validating data: ValidationError(Deployment.spec): missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false`

Reverting back the change resolved the issue:

`msdatawork@cloudshell:frontend-helidon (us-phoenix-1)$ head -1 frontend-helidon-deployment.yaml `
`apiVersion: extensions/v1beta1`
`msdatawork@cloudshell:frontend-helidon (us-phoenix-1)$ ./deploy.sh`
`deployment.extensions/frontend-helidon created`
`service/frontend created`
`msdatawork@cloudshell:frontend-helidon (us-phoenix-1)$`

**Comment by paulparkinson** [comment]
fixed, thanks!
