### ISSUE TITLE
helidonatp image fails build during first try

### ISSUE THREAD

**Issue by lichsmarac** [paulparkinson/msdataworkshop#4]
https://github.com/paulparkinson/msdataworkshop/blob/6769355b77e758987a439656d7a0a43f7da5d142/build.sh#L18

When running the msdataworkshop/build.sh for the first time, the helidonatp fails build with maven complaining on missing aq jar file. 

On second run of msdataworkshop/build.sh the issue goes away, and helidonatp is successfully built and pushed into the OCIR repo. 

If the maven install aq and soda step is prior to atpaqadmin step, this might potentially eliminate the error.

**Comment by paulparkinson** [comment]
fixed, thanks!
